-- V1: Limpeza do schema - Drop de todas as tabelas

DROP TABLE IF EXISTS employee_invites CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS yard_employees CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS yard_vehicles CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS bookings CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS qr_codes CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS yards CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS vehicles CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS models CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS roles CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS users CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS addresses CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS logs CASCADE CONSTRAINTS;
